trunk-version = "^0.21.9"
# https://trunkrs.dev/configuration/

[build]
target = "index.html"       # The index HTML file to drive the bundling process.
html_output = "index.html"  # The name of the output HTML file.
release = true             # Build in release mode.
dist = "dist"               # The output dir for all final assets.
# https://github.com/trunk-rs/trunk/issues/268#issuecomment-955653986
# github pages loads assets from username.github.io/repo_name/<path> rather than
# username.github.io/path. We fix this with public_url
#
# The public URL from which assets are to be served.
public_url = "/hexgridspiral-example"           
filehash = true             # Whether to include hash values in the output file names.
inject_scripts = true       # Whether to inject scripts (and module preloads) into the finalized output.
offline = false             # Run without network access
frozen = false              # Require Cargo.lock and cache are up to date
locked = false              # Require Cargo.lock is up to date
minify = "on_release"            # Control minification: can be one of: never, on_release, always
